### ISSUE TITLE
TODO list on 11 September 2020

### ISSUE THREAD

**Issue by CheerWizard** [MercuriiWorks/Hazel#1]
- [ ] Create merge request for dev;

- [ ] Merge last added branch of "feature" namespace into dev;

- [ ] Review code and make small refactoring.
